dist: xenial
language: sh
script: echo ok
os:
  - linux
  - osx
env:
  - SH=bash
  - SH=zsh
  - SH=ksh
addons:
  apt:
    update: true
  homebew:
    update: true
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y "$SH"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install "$SH"; fi

