dist: xenial
language: sh
script: echo ok
os:
  - linux
  - osx
osx_image: xcode10.1
env:
  - SH=bash
  - SH=zsh
  - SH=ksh
addons:
  apt:
    update: true
  homebew:
    update: true
before_install:
  - |
    case $TRAVIS_OS_NAME in
      linux) sudo apt-get install -y "$SH" ;;
      osx) brew install "$SH" ;;
    esac

